dom0_hosts:
  - ams-ps.ooni.nu
  - ams-slack-1.ooni.org
  - amsmatomo.ooni.nu
  - db-1.proteus.ooni.io
  - doams1-countly.ooni.nu
  - mia-echoth.ooni.nu
  - mia-httpth.ooni.nu

blackbox_jobs:
  - name: "ooni web_connectivity test helpers"
    module: "ooni_web_connectivity_ok"
    targets:
      # - "https://a.web-connectivity.th.ooni.io/status"
      - "https://wcth.ooni.io/status"
      # TODO add these records to the ALB config
      #- "https://ams-wcth2.ooni.nu/status"
      #- "https://a.web-connectivity.th.ooni.io/status" # "https://ams-wcth3.ooni.nu/status"
      # cloudfront
      - "https://d33d1gs9kpq1c5.cloudfront.net/status"

  - name: "new test helpers"
    module: "new_test_helper_health"
    targets:
      - "https://0.th.ooni.org/"
      - "https://1.th.ooni.org/"
      - "https://2.th.ooni.org/"
      - "https://3.th.ooni.org/"
      - "https://4.th.ooni.org/"
      - "https://5.th.ooni.org/"
      - "https://6.th.ooni.org/"

  - name: "ooni collector"
    module: "ooni_collector_ok"
    targets:
      # - "https://a.collector.ooni.io/invalidpath"
      - "https://b.collector.ooni.io/invalidpath" # hardcoded in MK as a fallback in case of bouncer failure
      - "https://c.collector.ooni.io/invalidpath"
      # cloudfront
      - "https://dkyhjv0wpi2dk.cloudfront.net/invalidpath"
      - "https://dvp6h0xblpcqp.cloudfront.net/invalidpath"
      # Probe services
      - "https://ps.ooni.io/invalidpath"
      - "https://collector.ooni.io/invalidpath"

  - name: "ooni bouncer"
    module: "ooni_bouncer_ok"
    targets:
      - "https://bouncer.ooni.io/bouncer/net-tests"
      - "https://ps.ooni.io/bouncer/net-tests"
      # cloudfront
      - "https://d3kr4emv7f56qa.cloudfront.net/bouncer/net-tests"

  # IP addresses are used for test-helpers in monitoring configuration for some
  # historical reason hopefully remembered by @hellais.
  - name: "ooni tcp echo"
    module: "ooni_tcp_echo_ok"
    targets:
      - "{{ lookup('dig', 'c.echo.th.ooni.io/A') }}:80"

  - name: "ooni http return json headers"
    module: "ooni_http_return_json_headers_ok"
    targets:
      - "http://{{ lookup('dig', 'a.http.th.ooni.io/A') }}:80"

  - name: "ooni explorer homepage"
    module: "http_2xx"
    targets:
      - "https://explorer.ooni.org/"

  # API #

  - name: "ooni API measurements"
    module: "http_2xx"
    targets:
      - "https://api.ooni.io/api/v1/measurements"
      - "https://api.ooni.org/api/v1/measurements"

  - name: "ooni API test-list urls"
    module: "https_2xx_json_meta"
    targets:
      - "https://api.ooni.io/api/v1/test-list/urls?country_code=US"
      - "https://api.ooni.org/api/v1/test-list/urls?country_code=US"

  - name: "ooni API test-helpers"
    module: "https_2xx_json"
    targets:
      - "https://api.ooni.io/api/v1/test-helpers"
      - "https://api.ooni.org/api/v1/test-helpers"

  - name: "ooni API priv global overview"
    module: "https_2xx_json"
    targets:
      - "https://api.ooni.io/api/_/global_overview"
      - "https://api.ooni.org/api/_/global_overview"

  - name: "ooni API findings listing"
    module: "https_2xx_json"
    targets:
      - "https://api.ooni.io/api/v1/incidents/search"
      - "https://api.ooni.org/api/v1/incidents/search"

  # Note: this always returns true by design
  - name: "OONI API check_report_id"
    module: "https_2xx_json"
    targets:
      - "https://api.ooni.io/api/_/check_report_id?report_id=RANDOM"
      - "https://api.ooni.org/api/_/check_report_id?report_id=RANDOM"

  - name: "OONI API raw_measurement"
    module: "https_2xx_json"
    targets:
      - "https://api.ooni.io/api/v1/raw_measurement?measurement_uid=20240924151005.116855_IT_httpinvalidrequestline_f63463817af9eebe"
      - "https://api.ooni.org/api/v1/raw_measurement?measurement_uid=20240924151005.116855_IT_httpinvalidrequestline_f63463817af9eebe"

  - name: "OONI Run v2 API"
    module: "https_2xx_json"
    targets:
      - "https://api.ooni.org/api/v2/oonirun/links/10009"
      - "https://api.ooni.org/api/v2/oonirun/links/10009/revisions"

  # end of API #

  - name: "countly.ooni.io ping"
    module: "http_2xx"
    targets:
      - "https://countly.ooni.io/o/ping"

  - name: "slack inviter"
    module: "http_2xx"
    targets:
      - "https://slack.ooni.org"

  - name: "ooni website"
    module: "http_2xx"
    targets:
      - "https://ooni.torproject.org"
      - "https://ooni.org"

  - name: "orchestrate"
    module: "ooni_orchestrate"
    targets: ["https://orchestrate.ooni.io:443/api/v1/test-list/urls?limit=10"]

  - name: "registry"
    module: "ooni_registry"
    targets: ["https://registry.proteus.ooni.io:443/api/v1/register"]

  - name: ssh
    module: ssh_banner
    targets: "{{ dom0_hosts | map('regex_replace', '$', ':22') | list }}"

  - name: icmp
    module: icmp
    targets: "{{ dom0_hosts | list }}"
