- name: Restart jupyterhub
  ansible.builtin.systemd_service:
    name: jupyterhub
    state: restarted
    daemon_reload: true
- name: Restart oonipipeline-worker
  ansible.builtin.systemd_service:
    name: oonipipeline-worker
    state: restarted
    daemon_reload: true

- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
