---
- name: Deploy oonidata clickhouse hosts
  hosts:
    - notebook.ooni.org
    - data1.htz-fsn.prod.ooni.nu
    - data2.htz-fsn.prod.ooni.nu
    - data3.htz-fsn.prod.ooni.nu
  become: true
  tags:
    - clickhouse
  roles:
    # - prometheus_node_exporter
    - oonidata_clickhouse
