---
- name: ClickHouse servers
  hosts: clickhouse_servers
  user: admin
  become: yes
  vars:
    clickhouse_reader_password: "{{ lookup('env', 'CLICKHOUSE_READER_PASSWORD') }}"
  roles:
    - clickhouse
  handlers:
    - name: restart clickhouse-server
      service:
        name: clickhouse-server
        state: restarted

- name: Update monitoring config
  hosts: monitoring.ooni.org
  become: yes
  roles:
    - prometheus
    - prometheus_blackbox_exporter
    - prometheus_alertmanager

- name: Setup OpenVPN server
  hosts: openvpn-server1.ooni.io
  become: true
  remote_user: root
  roles:
    - ssh_users

- name: Setup codesign box
  hosts: codesign-box
  become: true
  remote_user: ubuntu
  roles:
    - codesign_box
