---
- name: Ensure all hosts are bootstrapped correctly
  hosts: all
  become: yes
  roles:
    - bootstrap

- name: ClickHouse servers
  hosts: clickhouse_servers
  user: admin
  become: true
  vars:
    clickhouse_reader_password: "{{ lookup('env', 'CLICKHOUSE_READER_PASSWORD') }}"
  roles:
    - clickhouse
  handlers:
    - name: Restart clickhouse-server
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

- name: Update monitoring config
  hosts: monitoring.ooni.org
  become: true
  roles:
    - prometheus
    - prometheus_blackbox_exporter
    - prometheus_alertmanager

- name: Deploy data.ooni.org host
  hosts: data.ooni.org
  become: true
  roles:
    #- clickhouse
    - ssh_users
    #- jupyterhub

- name: Setup OpenVPN server
  hosts: openvpn-server1.ooni.io
  become: true
  remote_user: root
  roles:
    - ssh_users

- name: Deploy oonidata hosts
  hosts: oonidata.ooni.org
  become: true
  roles:
    - oonidata

- name: Deploy notebook hosts
  hosts: notebook.ooni.org
  become: true
  vars:
    enable_oonipipeline_worker: false
  roles:
    - oonidata

# commented out due to the fact it requires manual config of ~/.ssh/config
#- name: Setup codesign box
#  hosts: codesign-box
#  become: true
#  remote_user: ubuntu
#  roles:
#    - codesign_box
