---
- name: ClickHouse servers
  hosts: clickhouse_servers
  user: admin
  become: yes
  vars:
    clickhouse_reader_password: "{{ lookup('env', 'CLICKHOUSE_READER_PASSWORD') }}"
  roles:
    - clickhouse
  handlers:
    - name: restart clickhouse-server
      service:
        name: clickhouse-server
        state: restarted

- name: Update monitoring config
  hosts: monitoring.ooni.org
  roles:
    - prometheus
